### ISSUE TITLE
Support React 18

### ISSUE THREAD

**Issue by afenton90** [gocardless/react-dropin#15]
React 18 is now generally available. At the moment the `peerDependencies` stipulate:
```json
 "peerDependencies": {
    "react": "^16.8.0 || ^17.0.0",
    "react-dom": "^16.8.0 || ^17.0.0"
  },
```

Could the package be updated to support React 18?
I don't mind creating a PR for this, but I wanted to check that no one else has picked this up already.

**Comment by rliddler** [comment]
I don't think anyone on our side has picked this up so if you have a PR ready we'd be more than happy to have a look!

**Comment by afenton90** [comment]
Awesome! I'm guna work on this today. Thanks @rliddler 👍

**Comment by afenton90** [comment]
@rliddler checkout the PR to add support for React 18. I've added all the details of what's changed in the description, but of course if there are any questions do let me know.
