### ISSUE TITLE
Upgrade to gocardless-nodejs@3.12.0 to also inherit got@11.8.5

### ISSUE THREAD

**Issue by afenton90** [gocardless/react-dropin#32]
Currently this package uses [`gocardless-nodejs@2.1.0`](https://github.com/gocardless/react-dropin/blob/master/package-lock.json#L12985) which has a dependency on [`got@10.2.2`](https://github.com/gocardless/gocardless-nodejs/blob/v2.1.0/package.json#L26). This version of `got` has a security vulnerability that has been discovered (full details [here](https://security.snyk.io/package/npm/got/10.7.0)).

Upgrading to `gocardless-nodejs@3.12.0` would allow this package to inherit the patched version of `got@11.8.5`.

If the maintainers are happy for me to take this, I'll put a PR together to do the upgrade?

**Comment by aniketmalandkar** [comment]
Hi @afenton90, Thanks for reporting an issue. Feel free to raise a PR 👍

**Comment by Alexander-Blair** [comment]
@sam-robson sorry if you're not the right person, but do you have the ability to approve the version bump?
